### ISSUE TITLE
generative morphing example

### ISSUE THREAD

**Issue by yaseryacoob** [schardong/ifmorph#1]
I would like to replicate your 3.4.2 section on Blending Generative models, something like Figure 5. I can't seem to see it anywhere in the repo. Can you please point me to where it is and or share a script?

thanks

**Comment by schardong** [comment]
Hello @yaseryacoob, sorry for the delay in answering.

The generative blendings are actually not in our repo. We use the Diffusion Autoencoders code directly (https://github.com/phizaz/diffae). We used the checkpoints available in their README, namely the FFHQ256 (with latent DPM, can sample).

Sorry for the confusion, we will clarify this in our README.

If you have any further questions, just ask!
